# Use the analysis options settings from the top level of the repo (not
# the ones from above, which include the `public_member_api_docs` rule).

include: ../../analysis_options.yaml

linter:
  rules:
    unawaited_futures: true
    curly_braces_in_flow_control_structures: true
    avoid_catches_without_on_clauses: true
    prefer_relative_imports: true
